apiVersion: apps/v1
kind: Deployment
metadata:
  name: insan
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insan
  template:
    metadata:
      labels:
        app: insan
    spec:
      containers:
      - name: insan
        image: insan:0.1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: insan
